version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - riccardoscalco
  assignees:
  - riccardoscalco
  ignore:
  - dependency-name: xo
    versions:
    - 0.36.1
    - 0.37.1
  - dependency-name: lodash
    versions:
    - 4.17.20
